name: build-and-publish-docs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: pego/dowhy-examples-notebooks-deps
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Poetry 1.1.14
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.14'
      
      - uses: actions/checkout@main
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
      
      - name: Install dependencies
        run: poetry install -E plotting

      - name: Build
        run: |
          # sphinx-multiversion invokes git internally. Its call to "git rev-parse --show-toplevel" throws the
          # following error: "fatal: detected dubious ownership in repository at '/__w/dowhy/dowhy'"
          # The following command avoids this.
          git config --global --add safe.directory /__w/dowhy/dowhy
          ./docs/generate_docs.sh
          
      - name: Commit and push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dowhy-docs
